/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.gsportal.core.service.base;

import aQute.bnd.annotation.ProviderType;

import com.liferay.gsportal.core.model.Client;
import com.liferay.gsportal.core.service.ClientLocalService;
import com.liferay.gsportal.core.service.persistence.ClientPersistence;
import com.liferay.gsportal.core.service.persistence.EngagementPersistence;
import com.liferay.gsportal.core.service.persistence.MemberOfFinder;
import com.liferay.gsportal.core.service.persistence.MemberOfPersistence;
import com.liferay.gsportal.core.service.persistence.ProjectPersistence;
import com.liferay.gsportal.core.service.persistence.StaffMemberPersistence;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalServiceRegistry;
import com.liferay.portal.kernel.service.persistence.AddressPersistence;
import com.liferay.portal.kernel.service.persistence.ClassNamePersistence;
import com.liferay.portal.kernel.service.persistence.UserPersistence;
import com.liferay.portal.kernel.service.persistence.WebsitePersistence;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the client local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.gsportal.core.service.impl.ClientLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.liferay.gsportal.core.service.impl.ClientLocalServiceImpl
 * @see com.liferay.gsportal.core.service.ClientLocalServiceUtil
 * @generated
 */
@ProviderType
public abstract class ClientLocalServiceBaseImpl extends BaseLocalServiceImpl
	implements ClientLocalService, IdentifiableOSGiService {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.liferay.gsportal.core.service.ClientLocalServiceUtil} to access the client local service.
	 */

	/**
	 * Adds the client to the database. Also notifies the appropriate model listeners.
	 *
	 * @param client the client
	 * @return the client that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public Client addClient(Client client) {
		client.setNew(true);

		return clientPersistence.update(client);
	}

	/**
	 * Creates a new client with the primary key. Does not add the client to the database.
	 *
	 * @param clientId the primary key for the new client
	 * @return the new client
	 */
	@Override
	public Client createClient(long clientId) {
		return clientPersistence.create(clientId);
	}

	/**
	 * Deletes the client with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param clientId the primary key of the client
	 * @return the client that was removed
	 * @throws PortalException if a client with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public Client deleteClient(long clientId) throws PortalException {
		return clientPersistence.remove(clientId);
	}

	/**
	 * Deletes the client from the database. Also notifies the appropriate model listeners.
	 *
	 * @param client the client
	 * @return the client that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public Client deleteClient(Client client) {
		return clientPersistence.remove(client);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(Client.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return clientPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.liferay.gsportal.core.model.impl.ClientModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end) {
		return clientPersistence.findWithDynamicQuery(dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.liferay.gsportal.core.model.impl.ClientModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end, OrderByComparator<T> orderByComparator) {
		return clientPersistence.findWithDynamicQuery(dynamicQuery, start, end,
			orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return clientPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery,
		Projection projection) {
		return clientPersistence.countWithDynamicQuery(dynamicQuery, projection);
	}

	@Override
	public Client fetchClient(long clientId) {
		return clientPersistence.fetchByPrimaryKey(clientId);
	}

	/**
	 * Returns the client with the primary key.
	 *
	 * @param clientId the primary key of the client
	 * @return the client
	 * @throws PortalException if a client with the primary key could not be found
	 */
	@Override
	public Client getClient(long clientId) throws PortalException {
		return clientPersistence.findByPrimaryKey(clientId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery = new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(clientLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(Client.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("clientId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery getIndexableActionableDynamicQuery() {
		IndexableActionableDynamicQuery indexableActionableDynamicQuery = new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(clientLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(Client.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName("clientId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {
		actionableDynamicQuery.setBaseLocalService(clientLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(Client.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("clientId");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {
		return clientLocalService.deleteClient((Client)persistedModel);
	}

	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {
		return clientPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the clients.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.liferay.gsportal.core.model.impl.ClientModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param start the lower bound of the range of clients
	 * @param end the upper bound of the range of clients (not inclusive)
	 * @return the range of clients
	 */
	@Override
	public List<Client> getClients(int start, int end) {
		return clientPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of clients.
	 *
	 * @return the number of clients
	 */
	@Override
	public int getClientsCount() {
		return clientPersistence.countAll();
	}

	/**
	 * Updates the client in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param client the client
	 * @return the client that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public Client updateClient(Client client) {
		return clientPersistence.update(client);
	}

	/**
	 * Returns the client local service.
	 *
	 * @return the client local service
	 */
	public ClientLocalService getClientLocalService() {
		return clientLocalService;
	}

	/**
	 * Sets the client local service.
	 *
	 * @param clientLocalService the client local service
	 */
	public void setClientLocalService(ClientLocalService clientLocalService) {
		this.clientLocalService = clientLocalService;
	}

	/**
	 * Returns the client persistence.
	 *
	 * @return the client persistence
	 */
	public ClientPersistence getClientPersistence() {
		return clientPersistence;
	}

	/**
	 * Sets the client persistence.
	 *
	 * @param clientPersistence the client persistence
	 */
	public void setClientPersistence(ClientPersistence clientPersistence) {
		this.clientPersistence = clientPersistence;
	}

	/**
	 * Returns the engagement local service.
	 *
	 * @return the engagement local service
	 */
	public com.liferay.gsportal.core.service.EngagementLocalService getEngagementLocalService() {
		return engagementLocalService;
	}

	/**
	 * Sets the engagement local service.
	 *
	 * @param engagementLocalService the engagement local service
	 */
	public void setEngagementLocalService(
		com.liferay.gsportal.core.service.EngagementLocalService engagementLocalService) {
		this.engagementLocalService = engagementLocalService;
	}

	/**
	 * Returns the engagement persistence.
	 *
	 * @return the engagement persistence
	 */
	public EngagementPersistence getEngagementPersistence() {
		return engagementPersistence;
	}

	/**
	 * Sets the engagement persistence.
	 *
	 * @param engagementPersistence the engagement persistence
	 */
	public void setEngagementPersistence(
		EngagementPersistence engagementPersistence) {
		this.engagementPersistence = engagementPersistence;
	}

	/**
	 * Returns the member of local service.
	 *
	 * @return the member of local service
	 */
	public com.liferay.gsportal.core.service.MemberOfLocalService getMemberOfLocalService() {
		return memberOfLocalService;
	}

	/**
	 * Sets the member of local service.
	 *
	 * @param memberOfLocalService the member of local service
	 */
	public void setMemberOfLocalService(
		com.liferay.gsportal.core.service.MemberOfLocalService memberOfLocalService) {
		this.memberOfLocalService = memberOfLocalService;
	}

	/**
	 * Returns the member of persistence.
	 *
	 * @return the member of persistence
	 */
	public MemberOfPersistence getMemberOfPersistence() {
		return memberOfPersistence;
	}

	/**
	 * Sets the member of persistence.
	 *
	 * @param memberOfPersistence the member of persistence
	 */
	public void setMemberOfPersistence(MemberOfPersistence memberOfPersistence) {
		this.memberOfPersistence = memberOfPersistence;
	}

	/**
	 * Returns the member of finder.
	 *
	 * @return the member of finder
	 */
	public MemberOfFinder getMemberOfFinder() {
		return memberOfFinder;
	}

	/**
	 * Sets the member of finder.
	 *
	 * @param memberOfFinder the member of finder
	 */
	public void setMemberOfFinder(MemberOfFinder memberOfFinder) {
		this.memberOfFinder = memberOfFinder;
	}

	/**
	 * Returns the project local service.
	 *
	 * @return the project local service
	 */
	public com.liferay.gsportal.core.service.ProjectLocalService getProjectLocalService() {
		return projectLocalService;
	}

	/**
	 * Sets the project local service.
	 *
	 * @param projectLocalService the project local service
	 */
	public void setProjectLocalService(
		com.liferay.gsportal.core.service.ProjectLocalService projectLocalService) {
		this.projectLocalService = projectLocalService;
	}

	/**
	 * Returns the project persistence.
	 *
	 * @return the project persistence
	 */
	public ProjectPersistence getProjectPersistence() {
		return projectPersistence;
	}

	/**
	 * Sets the project persistence.
	 *
	 * @param projectPersistence the project persistence
	 */
	public void setProjectPersistence(ProjectPersistence projectPersistence) {
		this.projectPersistence = projectPersistence;
	}

	/**
	 * Returns the staff member local service.
	 *
	 * @return the staff member local service
	 */
	public com.liferay.gsportal.core.service.StaffMemberLocalService getStaffMemberLocalService() {
		return staffMemberLocalService;
	}

	/**
	 * Sets the staff member local service.
	 *
	 * @param staffMemberLocalService the staff member local service
	 */
	public void setStaffMemberLocalService(
		com.liferay.gsportal.core.service.StaffMemberLocalService staffMemberLocalService) {
		this.staffMemberLocalService = staffMemberLocalService;
	}

	/**
	 * Returns the staff member persistence.
	 *
	 * @return the staff member persistence
	 */
	public StaffMemberPersistence getStaffMemberPersistence() {
		return staffMemberPersistence;
	}

	/**
	 * Sets the staff member persistence.
	 *
	 * @param staffMemberPersistence the staff member persistence
	 */
	public void setStaffMemberPersistence(
		StaffMemberPersistence staffMemberPersistence) {
		this.staffMemberPersistence = staffMemberPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the address local service.
	 *
	 * @return the address local service
	 */
	public com.liferay.portal.kernel.service.AddressLocalService getAddressLocalService() {
		return addressLocalService;
	}

	/**
	 * Sets the address local service.
	 *
	 * @param addressLocalService the address local service
	 */
	public void setAddressLocalService(
		com.liferay.portal.kernel.service.AddressLocalService addressLocalService) {
		this.addressLocalService = addressLocalService;
	}

	/**
	 * Returns the address persistence.
	 *
	 * @return the address persistence
	 */
	public AddressPersistence getAddressPersistence() {
		return addressPersistence;
	}

	/**
	 * Sets the address persistence.
	 *
	 * @param addressPersistence the address persistence
	 */
	public void setAddressPersistence(AddressPersistence addressPersistence) {
		this.addressPersistence = addressPersistence;
	}

	/**
	 * Returns the class name local service.
	 *
	 * @return the class name local service
	 */
	public com.liferay.portal.kernel.service.ClassNameLocalService getClassNameLocalService() {
		return classNameLocalService;
	}

	/**
	 * Sets the class name local service.
	 *
	 * @param classNameLocalService the class name local service
	 */
	public void setClassNameLocalService(
		com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService) {
		this.classNameLocalService = classNameLocalService;
	}

	/**
	 * Returns the class name persistence.
	 *
	 * @return the class name persistence
	 */
	public ClassNamePersistence getClassNamePersistence() {
		return classNamePersistence;
	}

	/**
	 * Sets the class name persistence.
	 *
	 * @param classNamePersistence the class name persistence
	 */
	public void setClassNamePersistence(
		ClassNamePersistence classNamePersistence) {
		this.classNamePersistence = classNamePersistence;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.kernel.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.kernel.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.kernel.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	/**
	 * Returns the website local service.
	 *
	 * @return the website local service
	 */
	public com.liferay.portal.kernel.service.WebsiteLocalService getWebsiteLocalService() {
		return websiteLocalService;
	}

	/**
	 * Sets the website local service.
	 *
	 * @param websiteLocalService the website local service
	 */
	public void setWebsiteLocalService(
		com.liferay.portal.kernel.service.WebsiteLocalService websiteLocalService) {
		this.websiteLocalService = websiteLocalService;
	}

	/**
	 * Returns the website persistence.
	 *
	 * @return the website persistence
	 */
	public WebsitePersistence getWebsitePersistence() {
		return websitePersistence;
	}

	/**
	 * Sets the website persistence.
	 *
	 * @param websitePersistence the website persistence
	 */
	public void setWebsitePersistence(WebsitePersistence websitePersistence) {
		this.websitePersistence = websitePersistence;
	}

	public void afterPropertiesSet() {
		persistedModelLocalServiceRegistry.register("com.liferay.gsportal.core.model.Client",
			clientLocalService);
	}

	public void destroy() {
		persistedModelLocalServiceRegistry.unregister(
			"com.liferay.gsportal.core.model.Client");
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return ClientLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return Client.class;
	}

	protected String getModelClassName() {
		return Client.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = clientPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = ClientLocalService.class)
	protected ClientLocalService clientLocalService;
	@BeanReference(type = ClientPersistence.class)
	protected ClientPersistence clientPersistence;
	@BeanReference(type = com.liferay.gsportal.core.service.EngagementLocalService.class)
	protected com.liferay.gsportal.core.service.EngagementLocalService engagementLocalService;
	@BeanReference(type = EngagementPersistence.class)
	protected EngagementPersistence engagementPersistence;
	@BeanReference(type = com.liferay.gsportal.core.service.MemberOfLocalService.class)
	protected com.liferay.gsportal.core.service.MemberOfLocalService memberOfLocalService;
	@BeanReference(type = MemberOfPersistence.class)
	protected MemberOfPersistence memberOfPersistence;
	@BeanReference(type = MemberOfFinder.class)
	protected MemberOfFinder memberOfFinder;
	@BeanReference(type = com.liferay.gsportal.core.service.ProjectLocalService.class)
	protected com.liferay.gsportal.core.service.ProjectLocalService projectLocalService;
	@BeanReference(type = ProjectPersistence.class)
	protected ProjectPersistence projectPersistence;
	@BeanReference(type = com.liferay.gsportal.core.service.StaffMemberLocalService.class)
	protected com.liferay.gsportal.core.service.StaffMemberLocalService staffMemberLocalService;
	@BeanReference(type = StaffMemberPersistence.class)
	protected StaffMemberPersistence staffMemberPersistence;
	@ServiceReference(type = com.liferay.counter.kernel.service.CounterLocalService.class)
	protected com.liferay.counter.kernel.service.CounterLocalService counterLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.AddressLocalService.class)
	protected com.liferay.portal.kernel.service.AddressLocalService addressLocalService;
	@ServiceReference(type = AddressPersistence.class)
	protected AddressPersistence addressPersistence;
	@ServiceReference(type = com.liferay.portal.kernel.service.ClassNameLocalService.class)
	protected com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService;
	@ServiceReference(type = ClassNamePersistence.class)
	protected ClassNamePersistence classNamePersistence;
	@ServiceReference(type = com.liferay.portal.kernel.service.ResourceLocalService.class)
	protected com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.UserLocalService.class)
	protected com.liferay.portal.kernel.service.UserLocalService userLocalService;
	@ServiceReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	@ServiceReference(type = com.liferay.portal.kernel.service.WebsiteLocalService.class)
	protected com.liferay.portal.kernel.service.WebsiteLocalService websiteLocalService;
	@ServiceReference(type = WebsitePersistence.class)
	protected WebsitePersistence websitePersistence;
	@ServiceReference(type = PersistedModelLocalServiceRegistry.class)
	protected PersistedModelLocalServiceRegistry persistedModelLocalServiceRegistry;
}