/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.gsportal.core.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.gsportal.core.model.Client;
import com.liferay.gsportal.core.model.ClientModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the Client service. Represents a row in the &quot;Core_Client&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link ClientModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ClientImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ClientImpl
 * @see Client
 * @see ClientModel
 * @generated
 */
@ProviderType
public class ClientModelImpl extends BaseModelImpl<Client>
	implements ClientModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a client model instance should use the {@link Client} interface instead.
	 */
	public static final String TABLE_NAME = "Core_Client";
	public static final Object[][] TABLE_COLUMNS = {
			{ "clientId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "parentClientId", Types.BIGINT },
			{ "name", Types.VARCHAR },
			{ "description", Types.VARCHAR },
			{ "dashboardUrl", Types.VARCHAR },
			{ "logoId", Types.BIGINT },
			{ "logoUrl", Types.VARCHAR },
			{ "websiteUrl", Types.VARCHAR },
			{ "addressId", Types.BIGINT },
			{ "active_", Types.BOOLEAN }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("clientId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("parentClientId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("description", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("dashboardUrl", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("logoId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("logoUrl", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("websiteUrl", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("addressId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("active_", Types.BOOLEAN);
	}

	public static final String TABLE_SQL_CREATE = "create table Core_Client (clientId LONG not null primary key,companyId LONG,createDate DATE null,modifiedDate DATE null,parentClientId LONG,name VARCHAR(75) null,description STRING null,dashboardUrl VARCHAR(75) null,logoId LONG,logoUrl VARCHAR(75) null,websiteUrl VARCHAR(75) null,addressId LONG,active_ BOOLEAN)";
	public static final String TABLE_SQL_DROP = "drop table Core_Client";
	public static final String ORDER_BY_JPQL = " ORDER BY client.modifiedDate DESC";
	public static final String ORDER_BY_SQL = " ORDER BY Core_Client.modifiedDate DESC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.gsportal.core.service.util.PropsUtil.get(
				"value.object.entity.cache.enabled.com.liferay.gsportal.core.model.Client"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.gsportal.core.service.util.PropsUtil.get(
				"value.object.finder.cache.enabled.com.liferay.gsportal.core.model.Client"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.gsportal.core.service.util.PropsUtil.get(
				"value.object.column.bitmask.enabled.com.liferay.gsportal.core.model.Client"),
			true);
	public static final long PARENTCLIENTID_COLUMN_BITMASK = 1L;
	public static final long MODIFIEDDATE_COLUMN_BITMASK = 2L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.gsportal.core.service.util.PropsUtil.get(
				"lock.expiration.time.com.liferay.gsportal.core.model.Client"));

	public ClientModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _clientId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setClientId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _clientId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Client.class;
	}

	@Override
	public String getModelClassName() {
		return Client.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("clientId", getClientId());
		attributes.put("companyId", getCompanyId());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("parentClientId", getParentClientId());
		attributes.put("name", getName());
		attributes.put("description", getDescription());
		attributes.put("dashboardUrl", getDashboardUrl());
		attributes.put("logoId", getLogoId());
		attributes.put("logoUrl", getLogoUrl());
		attributes.put("websiteUrl", getWebsiteUrl());
		attributes.put("addressId", getAddressId());
		attributes.put("active", getActive());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long clientId = (Long)attributes.get("clientId");

		if (clientId != null) {
			setClientId(clientId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		Long parentClientId = (Long)attributes.get("parentClientId");

		if (parentClientId != null) {
			setParentClientId(parentClientId);
		}

		String name = (String)attributes.get("name");

		if (name != null) {
			setName(name);
		}

		String description = (String)attributes.get("description");

		if (description != null) {
			setDescription(description);
		}

		String dashboardUrl = (String)attributes.get("dashboardUrl");

		if (dashboardUrl != null) {
			setDashboardUrl(dashboardUrl);
		}

		Long logoId = (Long)attributes.get("logoId");

		if (logoId != null) {
			setLogoId(logoId);
		}

		String logoUrl = (String)attributes.get("logoUrl");

		if (logoUrl != null) {
			setLogoUrl(logoUrl);
		}

		String websiteUrl = (String)attributes.get("websiteUrl");

		if (websiteUrl != null) {
			setWebsiteUrl(websiteUrl);
		}

		Long addressId = (Long)attributes.get("addressId");

		if (addressId != null) {
			setAddressId(addressId);
		}

		Boolean active = (Boolean)attributes.get("active");

		if (active != null) {
			setActive(active);
		}
	}

	@Override
	public long getClientId() {
		return _clientId;
	}

	@Override
	public void setClientId(long clientId) {
		_clientId = clientId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_columnBitmask = -1L;

		_modifiedDate = modifiedDate;
	}

	@Override
	public long getParentClientId() {
		return _parentClientId;
	}

	@Override
	public void setParentClientId(long parentClientId) {
		_columnBitmask |= PARENTCLIENTID_COLUMN_BITMASK;

		if (!_setOriginalParentClientId) {
			_setOriginalParentClientId = true;

			_originalParentClientId = _parentClientId;
		}

		_parentClientId = parentClientId;
	}

	public long getOriginalParentClientId() {
		return _originalParentClientId;
	}

	@Override
	public String getName() {
		if (_name == null) {
			return StringPool.BLANK;
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_name = name;
	}

	@Override
	public String getDescription() {
		if (_description == null) {
			return StringPool.BLANK;
		}
		else {
			return _description;
		}
	}

	@Override
	public void setDescription(String description) {
		_description = description;
	}

	@Override
	public String getDashboardUrl() {
		if (_dashboardUrl == null) {
			return StringPool.BLANK;
		}
		else {
			return _dashboardUrl;
		}
	}

	@Override
	public void setDashboardUrl(String dashboardUrl) {
		_dashboardUrl = dashboardUrl;
	}

	@Override
	public long getLogoId() {
		return _logoId;
	}

	@Override
	public void setLogoId(long logoId) {
		_logoId = logoId;
	}

	@Override
	public String getLogoUrl() {
		if (_logoUrl == null) {
			return StringPool.BLANK;
		}
		else {
			return _logoUrl;
		}
	}

	@Override
	public void setLogoUrl(String logoUrl) {
		_logoUrl = logoUrl;
	}

	@Override
	public String getWebsiteUrl() {
		if (_websiteUrl == null) {
			return StringPool.BLANK;
		}
		else {
			return _websiteUrl;
		}
	}

	@Override
	public void setWebsiteUrl(String websiteUrl) {
		_websiteUrl = websiteUrl;
	}

	@Override
	public long getAddressId() {
		return _addressId;
	}

	@Override
	public void setAddressId(long addressId) {
		_addressId = addressId;
	}

	@Override
	public boolean getActive() {
		return _active;
	}

	@Override
	public boolean isActive() {
		return _active;
	}

	@Override
	public void setActive(boolean active) {
		_active = active;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			Client.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Client toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (Client)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ClientImpl clientImpl = new ClientImpl();

		clientImpl.setClientId(getClientId());
		clientImpl.setCompanyId(getCompanyId());
		clientImpl.setCreateDate(getCreateDate());
		clientImpl.setModifiedDate(getModifiedDate());
		clientImpl.setParentClientId(getParentClientId());
		clientImpl.setName(getName());
		clientImpl.setDescription(getDescription());
		clientImpl.setDashboardUrl(getDashboardUrl());
		clientImpl.setLogoId(getLogoId());
		clientImpl.setLogoUrl(getLogoUrl());
		clientImpl.setWebsiteUrl(getWebsiteUrl());
		clientImpl.setAddressId(getAddressId());
		clientImpl.setActive(getActive());

		clientImpl.resetOriginalValues();

		return clientImpl;
	}

	@Override
	public int compareTo(Client client) {
		int value = 0;

		value = DateUtil.compareTo(getModifiedDate(), client.getModifiedDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Client)) {
			return false;
		}

		Client client = (Client)obj;

		long primaryKey = client.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		ClientModelImpl clientModelImpl = this;

		clientModelImpl._setModifiedDate = false;

		clientModelImpl._originalParentClientId = clientModelImpl._parentClientId;

		clientModelImpl._setOriginalParentClientId = false;

		clientModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Client> toCacheModel() {
		ClientCacheModel clientCacheModel = new ClientCacheModel();

		clientCacheModel.clientId = getClientId();

		clientCacheModel.companyId = getCompanyId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			clientCacheModel.createDate = createDate.getTime();
		}
		else {
			clientCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			clientCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			clientCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		clientCacheModel.parentClientId = getParentClientId();

		clientCacheModel.name = getName();

		String name = clientCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			clientCacheModel.name = null;
		}

		clientCacheModel.description = getDescription();

		String description = clientCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			clientCacheModel.description = null;
		}

		clientCacheModel.dashboardUrl = getDashboardUrl();

		String dashboardUrl = clientCacheModel.dashboardUrl;

		if ((dashboardUrl != null) && (dashboardUrl.length() == 0)) {
			clientCacheModel.dashboardUrl = null;
		}

		clientCacheModel.logoId = getLogoId();

		clientCacheModel.logoUrl = getLogoUrl();

		String logoUrl = clientCacheModel.logoUrl;

		if ((logoUrl != null) && (logoUrl.length() == 0)) {
			clientCacheModel.logoUrl = null;
		}

		clientCacheModel.websiteUrl = getWebsiteUrl();

		String websiteUrl = clientCacheModel.websiteUrl;

		if ((websiteUrl != null) && (websiteUrl.length() == 0)) {
			clientCacheModel.websiteUrl = null;
		}

		clientCacheModel.addressId = getAddressId();

		clientCacheModel.active = getActive();

		return clientCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(27);

		sb.append("{clientId=");
		sb.append(getClientId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", parentClientId=");
		sb.append(getParentClientId());
		sb.append(", name=");
		sb.append(getName());
		sb.append(", description=");
		sb.append(getDescription());
		sb.append(", dashboardUrl=");
		sb.append(getDashboardUrl());
		sb.append(", logoId=");
		sb.append(getLogoId());
		sb.append(", logoUrl=");
		sb.append(getLogoUrl());
		sb.append(", websiteUrl=");
		sb.append(getWebsiteUrl());
		sb.append(", addressId=");
		sb.append(getAddressId());
		sb.append(", active=");
		sb.append(getActive());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(43);

		sb.append("<model><model-name>");
		sb.append("com.liferay.gsportal.core.model.Client");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>clientId</column-name><column-value><![CDATA[");
		sb.append(getClientId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>parentClientId</column-name><column-value><![CDATA[");
		sb.append(getParentClientId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>name</column-name><column-value><![CDATA[");
		sb.append(getName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>description</column-name><column-value><![CDATA[");
		sb.append(getDescription());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>dashboardUrl</column-name><column-value><![CDATA[");
		sb.append(getDashboardUrl());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>logoId</column-name><column-value><![CDATA[");
		sb.append(getLogoId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>logoUrl</column-name><column-value><![CDATA[");
		sb.append(getLogoUrl());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>websiteUrl</column-name><column-value><![CDATA[");
		sb.append(getWebsiteUrl());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>addressId</column-name><column-value><![CDATA[");
		sb.append(getAddressId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>active</column-name><column-value><![CDATA[");
		sb.append(getActive());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = Client.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			Client.class
		};
	private long _clientId;
	private long _companyId;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _parentClientId;
	private long _originalParentClientId;
	private boolean _setOriginalParentClientId;
	private String _name;
	private String _description;
	private String _dashboardUrl;
	private long _logoId;
	private String _logoUrl;
	private String _websiteUrl;
	private long _addressId;
	private boolean _active;
	private long _columnBitmask;
	private Client _escapedModel;
}