/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.gsportal.core.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.gsportal.core.model.Engagement;
import com.liferay.gsportal.core.model.EngagementModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the Engagement service. Represents a row in the &quot;Core_Engagement&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link EngagementModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EngagementImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EngagementImpl
 * @see Engagement
 * @see EngagementModel
 * @generated
 */
@ProviderType
public class EngagementModelImpl extends BaseModelImpl<Engagement>
	implements EngagementModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a engagement model instance should use the {@link Engagement} interface instead.
	 */
	public static final String TABLE_NAME = "Core_Engagement";
	public static final Object[][] TABLE_COLUMNS = {
			{ "engagementId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "calendarBookingId", Types.BIGINT },
			{ "clientId", Types.BIGINT },
			{ "projectId", Types.BIGINT },
			{ "title", Types.VARCHAR },
			{ "description", Types.VARCHAR },
			{ "leadUserId", Types.BIGINT },
			{ "leadName", Types.VARCHAR },
			{ "typeCategoryId", Types.BIGINT },
			{ "difficultyId", Types.INTEGER },
			{ "progressStatusId", Types.INTEGER },
			{ "approvalStatusId", Types.INTEGER }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("engagementId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("calendarBookingId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("clientId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("projectId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("title", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("description", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("leadUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("leadName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("typeCategoryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("difficultyId", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("progressStatusId", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("approvalStatusId", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE = "create table Core_Engagement (engagementId LONG not null primary key,companyId LONG,createDate DATE null,modifiedDate DATE null,calendarBookingId LONG,clientId LONG,projectId LONG,title VARCHAR(75) null,description STRING null,leadUserId LONG,leadName VARCHAR(75) null,typeCategoryId LONG,difficultyId INTEGER,progressStatusId INTEGER,approvalStatusId INTEGER)";
	public static final String TABLE_SQL_DROP = "drop table Core_Engagement";
	public static final String ORDER_BY_JPQL = " ORDER BY engagement.modifiedDate DESC";
	public static final String ORDER_BY_SQL = " ORDER BY Core_Engagement.modifiedDate DESC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.gsportal.core.service.util.PropsUtil.get(
				"value.object.entity.cache.enabled.com.liferay.gsportal.core.model.Engagement"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.gsportal.core.service.util.PropsUtil.get(
				"value.object.finder.cache.enabled.com.liferay.gsportal.core.model.Engagement"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.gsportal.core.service.util.PropsUtil.get(
				"value.object.column.bitmask.enabled.com.liferay.gsportal.core.model.Engagement"),
			true);
	public static final long PROJECTID_COLUMN_BITMASK = 1L;
	public static final long MODIFIEDDATE_COLUMN_BITMASK = 2L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.gsportal.core.service.util.PropsUtil.get(
				"lock.expiration.time.com.liferay.gsportal.core.model.Engagement"));

	public EngagementModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _engagementId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setEngagementId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _engagementId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Engagement.class;
	}

	@Override
	public String getModelClassName() {
		return Engagement.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("engagementId", getEngagementId());
		attributes.put("companyId", getCompanyId());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("calendarBookingId", getCalendarBookingId());
		attributes.put("clientId", getClientId());
		attributes.put("projectId", getProjectId());
		attributes.put("title", getTitle());
		attributes.put("description", getDescription());
		attributes.put("leadUserId", getLeadUserId());
		attributes.put("leadName", getLeadName());
		attributes.put("typeCategoryId", getTypeCategoryId());
		attributes.put("difficultyId", getDifficultyId());
		attributes.put("progressStatusId", getProgressStatusId());
		attributes.put("approvalStatusId", getApprovalStatusId());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long engagementId = (Long)attributes.get("engagementId");

		if (engagementId != null) {
			setEngagementId(engagementId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		Long calendarBookingId = (Long)attributes.get("calendarBookingId");

		if (calendarBookingId != null) {
			setCalendarBookingId(calendarBookingId);
		}

		Long clientId = (Long)attributes.get("clientId");

		if (clientId != null) {
			setClientId(clientId);
		}

		Long projectId = (Long)attributes.get("projectId");

		if (projectId != null) {
			setProjectId(projectId);
		}

		String title = (String)attributes.get("title");

		if (title != null) {
			setTitle(title);
		}

		String description = (String)attributes.get("description");

		if (description != null) {
			setDescription(description);
		}

		Long leadUserId = (Long)attributes.get("leadUserId");

		if (leadUserId != null) {
			setLeadUserId(leadUserId);
		}

		String leadName = (String)attributes.get("leadName");

		if (leadName != null) {
			setLeadName(leadName);
		}

		Long typeCategoryId = (Long)attributes.get("typeCategoryId");

		if (typeCategoryId != null) {
			setTypeCategoryId(typeCategoryId);
		}

		Integer difficultyId = (Integer)attributes.get("difficultyId");

		if (difficultyId != null) {
			setDifficultyId(difficultyId);
		}

		Integer progressStatusId = (Integer)attributes.get("progressStatusId");

		if (progressStatusId != null) {
			setProgressStatusId(progressStatusId);
		}

		Integer approvalStatusId = (Integer)attributes.get("approvalStatusId");

		if (approvalStatusId != null) {
			setApprovalStatusId(approvalStatusId);
		}
	}

	@Override
	public long getEngagementId() {
		return _engagementId;
	}

	@Override
	public void setEngagementId(long engagementId) {
		_engagementId = engagementId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_columnBitmask = -1L;

		_modifiedDate = modifiedDate;
	}

	@Override
	public long getCalendarBookingId() {
		return _calendarBookingId;
	}

	@Override
	public void setCalendarBookingId(long calendarBookingId) {
		_calendarBookingId = calendarBookingId;
	}

	@Override
	public long getClientId() {
		return _clientId;
	}

	@Override
	public void setClientId(long clientId) {
		_clientId = clientId;
	}

	@Override
	public long getProjectId() {
		return _projectId;
	}

	@Override
	public void setProjectId(long projectId) {
		_columnBitmask |= PROJECTID_COLUMN_BITMASK;

		if (!_setOriginalProjectId) {
			_setOriginalProjectId = true;

			_originalProjectId = _projectId;
		}

		_projectId = projectId;
	}

	public long getOriginalProjectId() {
		return _originalProjectId;
	}

	@Override
	public String getTitle() {
		if (_title == null) {
			return StringPool.BLANK;
		}
		else {
			return _title;
		}
	}

	@Override
	public void setTitle(String title) {
		_title = title;
	}

	@Override
	public String getDescription() {
		if (_description == null) {
			return StringPool.BLANK;
		}
		else {
			return _description;
		}
	}

	@Override
	public void setDescription(String description) {
		_description = description;
	}

	@Override
	public long getLeadUserId() {
		return _leadUserId;
	}

	@Override
	public void setLeadUserId(long leadUserId) {
		_leadUserId = leadUserId;
	}

	@Override
	public String getLeadUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getLeadUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return StringPool.BLANK;
		}
	}

	@Override
	public void setLeadUserUuid(String leadUserUuid) {
	}

	@Override
	public String getLeadName() {
		if (_leadName == null) {
			return StringPool.BLANK;
		}
		else {
			return _leadName;
		}
	}

	@Override
	public void setLeadName(String leadName) {
		_leadName = leadName;
	}

	@Override
	public long getTypeCategoryId() {
		return _typeCategoryId;
	}

	@Override
	public void setTypeCategoryId(long typeCategoryId) {
		_typeCategoryId = typeCategoryId;
	}

	@Override
	public int getDifficultyId() {
		return _difficultyId;
	}

	@Override
	public void setDifficultyId(int difficultyId) {
		_difficultyId = difficultyId;
	}

	@Override
	public int getProgressStatusId() {
		return _progressStatusId;
	}

	@Override
	public void setProgressStatusId(int progressStatusId) {
		_progressStatusId = progressStatusId;
	}

	@Override
	public int getApprovalStatusId() {
		return _approvalStatusId;
	}

	@Override
	public void setApprovalStatusId(int approvalStatusId) {
		_approvalStatusId = approvalStatusId;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			Engagement.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Engagement toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (Engagement)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		EngagementImpl engagementImpl = new EngagementImpl();

		engagementImpl.setEngagementId(getEngagementId());
		engagementImpl.setCompanyId(getCompanyId());
		engagementImpl.setCreateDate(getCreateDate());
		engagementImpl.setModifiedDate(getModifiedDate());
		engagementImpl.setCalendarBookingId(getCalendarBookingId());
		engagementImpl.setClientId(getClientId());
		engagementImpl.setProjectId(getProjectId());
		engagementImpl.setTitle(getTitle());
		engagementImpl.setDescription(getDescription());
		engagementImpl.setLeadUserId(getLeadUserId());
		engagementImpl.setLeadName(getLeadName());
		engagementImpl.setTypeCategoryId(getTypeCategoryId());
		engagementImpl.setDifficultyId(getDifficultyId());
		engagementImpl.setProgressStatusId(getProgressStatusId());
		engagementImpl.setApprovalStatusId(getApprovalStatusId());

		engagementImpl.resetOriginalValues();

		return engagementImpl;
	}

	@Override
	public int compareTo(Engagement engagement) {
		int value = 0;

		value = DateUtil.compareTo(getModifiedDate(),
				engagement.getModifiedDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Engagement)) {
			return false;
		}

		Engagement engagement = (Engagement)obj;

		long primaryKey = engagement.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		EngagementModelImpl engagementModelImpl = this;

		engagementModelImpl._setModifiedDate = false;

		engagementModelImpl._originalProjectId = engagementModelImpl._projectId;

		engagementModelImpl._setOriginalProjectId = false;

		engagementModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Engagement> toCacheModel() {
		EngagementCacheModel engagementCacheModel = new EngagementCacheModel();

		engagementCacheModel.engagementId = getEngagementId();

		engagementCacheModel.companyId = getCompanyId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			engagementCacheModel.createDate = createDate.getTime();
		}
		else {
			engagementCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			engagementCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			engagementCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		engagementCacheModel.calendarBookingId = getCalendarBookingId();

		engagementCacheModel.clientId = getClientId();

		engagementCacheModel.projectId = getProjectId();

		engagementCacheModel.title = getTitle();

		String title = engagementCacheModel.title;

		if ((title != null) && (title.length() == 0)) {
			engagementCacheModel.title = null;
		}

		engagementCacheModel.description = getDescription();

		String description = engagementCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			engagementCacheModel.description = null;
		}

		engagementCacheModel.leadUserId = getLeadUserId();

		engagementCacheModel.leadName = getLeadName();

		String leadName = engagementCacheModel.leadName;

		if ((leadName != null) && (leadName.length() == 0)) {
			engagementCacheModel.leadName = null;
		}

		engagementCacheModel.typeCategoryId = getTypeCategoryId();

		engagementCacheModel.difficultyId = getDifficultyId();

		engagementCacheModel.progressStatusId = getProgressStatusId();

		engagementCacheModel.approvalStatusId = getApprovalStatusId();

		return engagementCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(31);

		sb.append("{engagementId=");
		sb.append(getEngagementId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", calendarBookingId=");
		sb.append(getCalendarBookingId());
		sb.append(", clientId=");
		sb.append(getClientId());
		sb.append(", projectId=");
		sb.append(getProjectId());
		sb.append(", title=");
		sb.append(getTitle());
		sb.append(", description=");
		sb.append(getDescription());
		sb.append(", leadUserId=");
		sb.append(getLeadUserId());
		sb.append(", leadName=");
		sb.append(getLeadName());
		sb.append(", typeCategoryId=");
		sb.append(getTypeCategoryId());
		sb.append(", difficultyId=");
		sb.append(getDifficultyId());
		sb.append(", progressStatusId=");
		sb.append(getProgressStatusId());
		sb.append(", approvalStatusId=");
		sb.append(getApprovalStatusId());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(49);

		sb.append("<model><model-name>");
		sb.append("com.liferay.gsportal.core.model.Engagement");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>engagementId</column-name><column-value><![CDATA[");
		sb.append(getEngagementId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>calendarBookingId</column-name><column-value><![CDATA[");
		sb.append(getCalendarBookingId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>clientId</column-name><column-value><![CDATA[");
		sb.append(getClientId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>projectId</column-name><column-value><![CDATA[");
		sb.append(getProjectId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>title</column-name><column-value><![CDATA[");
		sb.append(getTitle());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>description</column-name><column-value><![CDATA[");
		sb.append(getDescription());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>leadUserId</column-name><column-value><![CDATA[");
		sb.append(getLeadUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>leadName</column-name><column-value><![CDATA[");
		sb.append(getLeadName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>typeCategoryId</column-name><column-value><![CDATA[");
		sb.append(getTypeCategoryId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>difficultyId</column-name><column-value><![CDATA[");
		sb.append(getDifficultyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>progressStatusId</column-name><column-value><![CDATA[");
		sb.append(getProgressStatusId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>approvalStatusId</column-name><column-value><![CDATA[");
		sb.append(getApprovalStatusId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = Engagement.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			Engagement.class
		};
	private long _engagementId;
	private long _companyId;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _calendarBookingId;
	private long _clientId;
	private long _projectId;
	private long _originalProjectId;
	private boolean _setOriginalProjectId;
	private String _title;
	private String _description;
	private long _leadUserId;
	private String _leadName;
	private long _typeCategoryId;
	private int _difficultyId;
	private int _progressStatusId;
	private int _approvalStatusId;
	private long _columnBitmask;
	private Engagement _escapedModel;
}