/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.gsportal.core.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.gsportal.core.model.MemberOf;
import com.liferay.gsportal.core.model.MemberOfModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the MemberOf service. Represents a row in the &quot;Core_MemberOf&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link MemberOfModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link MemberOfImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see MemberOfImpl
 * @see MemberOf
 * @see MemberOfModel
 * @generated
 */
@ProviderType
public class MemberOfModelImpl extends BaseModelImpl<MemberOf>
	implements MemberOfModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a member of model instance should use the {@link MemberOf} interface instead.
	 */
	public static final String TABLE_NAME = "Core_MemberOf";
	public static final Object[][] TABLE_COLUMNS = {
			{ "memberOfId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "createDate", Types.TIMESTAMP },
			{ "userId", Types.BIGINT },
			{ "clientId", Types.BIGINT },
			{ "projectId", Types.BIGINT },
			{ "engagementId", Types.BIGINT },
			{ "memberRoleId", Types.INTEGER }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("memberOfId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("clientId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("projectId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("engagementId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("memberRoleId", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE = "create table Core_MemberOf (memberOfId LONG not null primary key,companyId LONG,createDate DATE null,userId LONG,clientId LONG,projectId LONG,engagementId LONG,memberRoleId INTEGER)";
	public static final String TABLE_SQL_DROP = "drop table Core_MemberOf";
	public static final String ORDER_BY_JPQL = " ORDER BY memberOf.createDate DESC";
	public static final String ORDER_BY_SQL = " ORDER BY Core_MemberOf.createDate DESC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.gsportal.core.service.util.PropsUtil.get(
				"value.object.entity.cache.enabled.com.liferay.gsportal.core.model.MemberOf"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.gsportal.core.service.util.PropsUtil.get(
				"value.object.finder.cache.enabled.com.liferay.gsportal.core.model.MemberOf"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.gsportal.core.service.util.PropsUtil.get(
				"value.object.column.bitmask.enabled.com.liferay.gsportal.core.model.MemberOf"),
			true);
	public static final long CLIENTID_COLUMN_BITMASK = 1L;
	public static final long ENGAGEMENTID_COLUMN_BITMASK = 2L;
	public static final long PROJECTID_COLUMN_BITMASK = 4L;
	public static final long USERID_COLUMN_BITMASK = 8L;
	public static final long CREATEDATE_COLUMN_BITMASK = 16L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.gsportal.core.service.util.PropsUtil.get(
				"lock.expiration.time.com.liferay.gsportal.core.model.MemberOf"));

	public MemberOfModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _memberOfId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setMemberOfId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _memberOfId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return MemberOf.class;
	}

	@Override
	public String getModelClassName() {
		return MemberOf.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("memberOfId", getMemberOfId());
		attributes.put("companyId", getCompanyId());
		attributes.put("createDate", getCreateDate());
		attributes.put("userId", getUserId());
		attributes.put("clientId", getClientId());
		attributes.put("projectId", getProjectId());
		attributes.put("engagementId", getEngagementId());
		attributes.put("memberRoleId", getMemberRoleId());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long memberOfId = (Long)attributes.get("memberOfId");

		if (memberOfId != null) {
			setMemberOfId(memberOfId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		Long clientId = (Long)attributes.get("clientId");

		if (clientId != null) {
			setClientId(clientId);
		}

		Long projectId = (Long)attributes.get("projectId");

		if (projectId != null) {
			setProjectId(projectId);
		}

		Long engagementId = (Long)attributes.get("engagementId");

		if (engagementId != null) {
			setEngagementId(engagementId);
		}

		Integer memberRoleId = (Integer)attributes.get("memberRoleId");

		if (memberRoleId != null) {
			setMemberRoleId(memberRoleId);
		}
	}

	@Override
	public long getMemberOfId() {
		return _memberOfId;
	}

	@Override
	public void setMemberOfId(long memberOfId) {
		_memberOfId = memberOfId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_columnBitmask = -1L;

		_createDate = createDate;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_columnBitmask |= USERID_COLUMN_BITMASK;

		if (!_setOriginalUserId) {
			_setOriginalUserId = true;

			_originalUserId = _userId;
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return StringPool.BLANK;
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	public long getOriginalUserId() {
		return _originalUserId;
	}

	@Override
	public long getClientId() {
		return _clientId;
	}

	@Override
	public void setClientId(long clientId) {
		_columnBitmask |= CLIENTID_COLUMN_BITMASK;

		if (!_setOriginalClientId) {
			_setOriginalClientId = true;

			_originalClientId = _clientId;
		}

		_clientId = clientId;
	}

	public long getOriginalClientId() {
		return _originalClientId;
	}

	@Override
	public long getProjectId() {
		return _projectId;
	}

	@Override
	public void setProjectId(long projectId) {
		_columnBitmask |= PROJECTID_COLUMN_BITMASK;

		if (!_setOriginalProjectId) {
			_setOriginalProjectId = true;

			_originalProjectId = _projectId;
		}

		_projectId = projectId;
	}

	public long getOriginalProjectId() {
		return _originalProjectId;
	}

	@Override
	public long getEngagementId() {
		return _engagementId;
	}

	@Override
	public void setEngagementId(long engagementId) {
		_columnBitmask |= ENGAGEMENTID_COLUMN_BITMASK;

		if (!_setOriginalEngagementId) {
			_setOriginalEngagementId = true;

			_originalEngagementId = _engagementId;
		}

		_engagementId = engagementId;
	}

	public long getOriginalEngagementId() {
		return _originalEngagementId;
	}

	@Override
	public int getMemberRoleId() {
		return _memberRoleId;
	}

	@Override
	public void setMemberRoleId(int memberRoleId) {
		_memberRoleId = memberRoleId;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			MemberOf.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public MemberOf toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (MemberOf)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		MemberOfImpl memberOfImpl = new MemberOfImpl();

		memberOfImpl.setMemberOfId(getMemberOfId());
		memberOfImpl.setCompanyId(getCompanyId());
		memberOfImpl.setCreateDate(getCreateDate());
		memberOfImpl.setUserId(getUserId());
		memberOfImpl.setClientId(getClientId());
		memberOfImpl.setProjectId(getProjectId());
		memberOfImpl.setEngagementId(getEngagementId());
		memberOfImpl.setMemberRoleId(getMemberRoleId());

		memberOfImpl.resetOriginalValues();

		return memberOfImpl;
	}

	@Override
	public int compareTo(MemberOf memberOf) {
		int value = 0;

		value = DateUtil.compareTo(getCreateDate(), memberOf.getCreateDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof MemberOf)) {
			return false;
		}

		MemberOf memberOf = (MemberOf)obj;

		long primaryKey = memberOf.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		MemberOfModelImpl memberOfModelImpl = this;

		memberOfModelImpl._originalUserId = memberOfModelImpl._userId;

		memberOfModelImpl._setOriginalUserId = false;

		memberOfModelImpl._originalClientId = memberOfModelImpl._clientId;

		memberOfModelImpl._setOriginalClientId = false;

		memberOfModelImpl._originalProjectId = memberOfModelImpl._projectId;

		memberOfModelImpl._setOriginalProjectId = false;

		memberOfModelImpl._originalEngagementId = memberOfModelImpl._engagementId;

		memberOfModelImpl._setOriginalEngagementId = false;

		memberOfModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<MemberOf> toCacheModel() {
		MemberOfCacheModel memberOfCacheModel = new MemberOfCacheModel();

		memberOfCacheModel.memberOfId = getMemberOfId();

		memberOfCacheModel.companyId = getCompanyId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			memberOfCacheModel.createDate = createDate.getTime();
		}
		else {
			memberOfCacheModel.createDate = Long.MIN_VALUE;
		}

		memberOfCacheModel.userId = getUserId();

		memberOfCacheModel.clientId = getClientId();

		memberOfCacheModel.projectId = getProjectId();

		memberOfCacheModel.engagementId = getEngagementId();

		memberOfCacheModel.memberRoleId = getMemberRoleId();

		return memberOfCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(17);

		sb.append("{memberOfId=");
		sb.append(getMemberOfId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", clientId=");
		sb.append(getClientId());
		sb.append(", projectId=");
		sb.append(getProjectId());
		sb.append(", engagementId=");
		sb.append(getEngagementId());
		sb.append(", memberRoleId=");
		sb.append(getMemberRoleId());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(28);

		sb.append("<model><model-name>");
		sb.append("com.liferay.gsportal.core.model.MemberOf");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>memberOfId</column-name><column-value><![CDATA[");
		sb.append(getMemberOfId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>clientId</column-name><column-value><![CDATA[");
		sb.append(getClientId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>projectId</column-name><column-value><![CDATA[");
		sb.append(getProjectId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>engagementId</column-name><column-value><![CDATA[");
		sb.append(getEngagementId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>memberRoleId</column-name><column-value><![CDATA[");
		sb.append(getMemberRoleId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = MemberOf.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			MemberOf.class
		};
	private long _memberOfId;
	private long _companyId;
	private Date _createDate;
	private long _userId;
	private long _originalUserId;
	private boolean _setOriginalUserId;
	private long _clientId;
	private long _originalClientId;
	private boolean _setOriginalClientId;
	private long _projectId;
	private long _originalProjectId;
	private boolean _setOriginalProjectId;
	private long _engagementId;
	private long _originalEngagementId;
	private boolean _setOriginalEngagementId;
	private int _memberRoleId;
	private long _columnBitmask;
	private MemberOf _escapedModel;
}