/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.gsportal.core.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.gsportal.core.model.StaffMember;
import com.liferay.gsportal.core.model.StaffMemberModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the StaffMember service. Represents a row in the &quot;Core_StaffMember&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link StaffMemberModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link StaffMemberImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see StaffMemberImpl
 * @see StaffMember
 * @see StaffMemberModel
 * @generated
 */
@ProviderType
public class StaffMemberModelImpl extends BaseModelImpl<StaffMember>
	implements StaffMemberModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a staff member model instance should use the {@link StaffMember} interface instead.
	 */
	public static final String TABLE_NAME = "Core_StaffMember";
	public static final Object[][] TABLE_COLUMNS = {
			{ "userId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "employeeType", Types.INTEGER },
			{ "employerName", Types.VARCHAR }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("employeeType", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("employerName", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE = "create table Core_StaffMember (userId LONG not null primary key,companyId LONG,employeeType INTEGER,employerName VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table Core_StaffMember";
	public static final String ORDER_BY_JPQL = " ORDER BY staffMember.userId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY Core_StaffMember.userId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.gsportal.core.service.util.PropsUtil.get(
				"value.object.entity.cache.enabled.com.liferay.gsportal.core.model.StaffMember"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.gsportal.core.service.util.PropsUtil.get(
				"value.object.finder.cache.enabled.com.liferay.gsportal.core.model.StaffMember"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.gsportal.core.service.util.PropsUtil.get(
				"lock.expiration.time.com.liferay.gsportal.core.model.StaffMember"));

	public StaffMemberModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _userId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setUserId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _userId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return StaffMember.class;
	}

	@Override
	public String getModelClassName() {
		return StaffMember.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("userId", getUserId());
		attributes.put("companyId", getCompanyId());
		attributes.put("employeeType", getEmployeeType());
		attributes.put("employerName", getEmployerName());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Integer employeeType = (Integer)attributes.get("employeeType");

		if (employeeType != null) {
			setEmployeeType(employeeType);
		}

		String employerName = (String)attributes.get("employerName");

		if (employerName != null) {
			setEmployerName(employerName);
		}
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return StringPool.BLANK;
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@Override
	public int getEmployeeType() {
		return _employeeType;
	}

	@Override
	public void setEmployeeType(int employeeType) {
		_employeeType = employeeType;
	}

	@Override
	public String getEmployerName() {
		if (_employerName == null) {
			return StringPool.BLANK;
		}
		else {
			return _employerName;
		}
	}

	@Override
	public void setEmployerName(String employerName) {
		_employerName = employerName;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			StaffMember.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public StaffMember toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (StaffMember)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		StaffMemberImpl staffMemberImpl = new StaffMemberImpl();

		staffMemberImpl.setUserId(getUserId());
		staffMemberImpl.setCompanyId(getCompanyId());
		staffMemberImpl.setEmployeeType(getEmployeeType());
		staffMemberImpl.setEmployerName(getEmployerName());

		staffMemberImpl.resetOriginalValues();

		return staffMemberImpl;
	}

	@Override
	public int compareTo(StaffMember staffMember) {
		int value = 0;

		if (getUserId() < staffMember.getUserId()) {
			value = -1;
		}
		else if (getUserId() > staffMember.getUserId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof StaffMember)) {
			return false;
		}

		StaffMember staffMember = (StaffMember)obj;

		long primaryKey = staffMember.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<StaffMember> toCacheModel() {
		StaffMemberCacheModel staffMemberCacheModel = new StaffMemberCacheModel();

		staffMemberCacheModel.userId = getUserId();

		staffMemberCacheModel.companyId = getCompanyId();

		staffMemberCacheModel.employeeType = getEmployeeType();

		staffMemberCacheModel.employerName = getEmployerName();

		String employerName = staffMemberCacheModel.employerName;

		if ((employerName != null) && (employerName.length() == 0)) {
			staffMemberCacheModel.employerName = null;
		}

		return staffMemberCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(9);

		sb.append("{userId=");
		sb.append(getUserId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", employeeType=");
		sb.append(getEmployeeType());
		sb.append(", employerName=");
		sb.append(getEmployerName());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(16);

		sb.append("<model><model-name>");
		sb.append("com.liferay.gsportal.core.model.StaffMember");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>employeeType</column-name><column-value><![CDATA[");
		sb.append(getEmployeeType());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>employerName</column-name><column-value><![CDATA[");
		sb.append(getEmployerName());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = StaffMember.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			StaffMember.class
		};
	private long _userId;
	private long _companyId;
	private int _employeeType;
	private String _employerName;
	private StaffMember _escapedModel;
}