/**
 * Liferay Sites Headless API
 * A Java client JAR is available for use with the group ID \'com.liferay\', artifact ID \'com.liferay.headless.site.client\', and version \'1.0.19\'.
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Represents the site being created.
*/
export class Site {
    /**
    * The site\'s external reference code.
    */
    'externalReferenceCode'?: string;
    'friendlyUrlPath'?: string;
    'id'?: number;
    'key'?: string;
    /**
    * The default value is open.
    */
    'membershipType'?: Site.MembershipTypeEnum;
    'name': string;
    'parentSiteKey'?: string;
    'templateKey'?: string;
    'templateType'?: Site.TemplateTypeEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "externalReferenceCode",
            "baseName": "externalReferenceCode",
            "type": "string"
        },
        {
            "name": "friendlyUrlPath",
            "baseName": "friendlyUrlPath",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "key",
            "baseName": "key",
            "type": "string"
        },
        {
            "name": "membershipType",
            "baseName": "membershipType",
            "type": "Site.MembershipTypeEnum"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "parentSiteKey",
            "baseName": "parentSiteKey",
            "type": "string"
        },
        {
            "name": "templateKey",
            "baseName": "templateKey",
            "type": "string"
        },
        {
            "name": "templateType",
            "baseName": "templateType",
            "type": "Site.TemplateTypeEnum"
        }    ];

    static getAttributeTypeMap() {
        return Site.attributeTypeMap;
    }
}

export namespace Site {
    export enum MembershipTypeEnum {
        Open = <any> 'open',
        Private = <any> 'private',
        Restricted = <any> 'restricted'
    }
    export enum TemplateTypeEnum {
        Initializer = <any> 'site-initializer',
        Template = <any> 'site-template'
    }
}
