/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.portal.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the RecentLayoutSet service. Represents a row in the &quot;RecentLayoutSet&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.portal.model.impl.RecentLayoutSetModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.portal.model.impl.RecentLayoutSetImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see RecentLayoutSet
 * @see com.liferay.portal.model.impl.RecentLayoutSetImpl
 * @see com.liferay.portal.model.impl.RecentLayoutSetModelImpl
 * @generated
 */
@ProviderType
public interface RecentLayoutSetModel extends BaseModel<RecentLayoutSet>,
	MVCCModel, ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a recent layout set model instance should use the {@link RecentLayoutSet} interface instead.
	 */

	/**
	 * Returns the primary key of this recent layout set.
	 *
	 * @return the primary key of this recent layout set
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this recent layout set.
	 *
	 * @param primaryKey the primary key of this recent layout set
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this recent layout set.
	 *
	 * @return the mvcc version of this recent layout set
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this recent layout set.
	 *
	 * @param mvccVersion the mvcc version of this recent layout set
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the recent layout set ID of this recent layout set.
	 *
	 * @return the recent layout set ID of this recent layout set
	 */
	public long getRecentLayoutSetId();

	/**
	 * Sets the recent layout set ID of this recent layout set.
	 *
	 * @param recentLayoutSetId the recent layout set ID of this recent layout set
	 */
	public void setRecentLayoutSetId(long recentLayoutSetId);

	/**
	 * Returns the group ID of this recent layout set.
	 *
	 * @return the group ID of this recent layout set
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this recent layout set.
	 *
	 * @param groupId the group ID of this recent layout set
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this recent layout set.
	 *
	 * @return the company ID of this recent layout set
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this recent layout set.
	 *
	 * @param companyId the company ID of this recent layout set
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this recent layout set.
	 *
	 * @return the user ID of this recent layout set
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this recent layout set.
	 *
	 * @param userId the user ID of this recent layout set
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this recent layout set.
	 *
	 * @return the user uuid of this recent layout set
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this recent layout set.
	 *
	 * @param userUuid the user uuid of this recent layout set
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the layout set ID of this recent layout set.
	 *
	 * @return the layout set ID of this recent layout set
	 */
	public long getLayoutSetId();

	/**
	 * Sets the layout set ID of this recent layout set.
	 *
	 * @param layoutSetId the layout set ID of this recent layout set
	 */
	public void setLayoutSetId(long layoutSetId);

	/**
	 * Returns the layout set branch ID of this recent layout set.
	 *
	 * @return the layout set branch ID of this recent layout set
	 */
	public long getLayoutSetBranchId();

	/**
	 * Sets the layout set branch ID of this recent layout set.
	 *
	 * @param layoutSetBranchId the layout set branch ID of this recent layout set
	 */
	public void setLayoutSetBranchId(long layoutSetBranchId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.liferay.portal.model.RecentLayoutSet recentLayoutSet);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.liferay.portal.model.RecentLayoutSet> toCacheModel();

	@Override
	public com.liferay.portal.model.RecentLayoutSet toEscapedModel();

	@Override
	public com.liferay.portal.model.RecentLayoutSet toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}