/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.batch.engine.model.impl;

import com.liferay.batch.engine.model.BatchEngineImportReportEntry;
import com.liferay.batch.engine.service.BatchEngineImportReportEntryLocalServiceUtil;

/**
 * The extended model base implementation for the BatchEngineImportReportEntry service. Represents a row in the &quot;BatchEngineImportReportEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link BatchEngineImportReportEntryImpl}.
 * </p>
 *
 * @author Shuyang Zhou
 * @see BatchEngineImportReportEntryImpl
 * @see BatchEngineImportReportEntry
 * @generated
 */
public abstract class BatchEngineImportReportEntryBaseImpl
	extends BatchEngineImportReportEntryModelImpl
	implements BatchEngineImportReportEntry {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a batch engine import report entry model instance should use the <code>BatchEngineImportReportEntry</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			BatchEngineImportReportEntryLocalServiceUtil.
				addBatchEngineImportReportEntry(this);
		}
		else {
			BatchEngineImportReportEntryLocalServiceUtil.
				updateBatchEngineImportReportEntry(this);
		}
	}

}