/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.batch.engine.model.impl;

import com.liferay.batch.engine.model.BatchEngineImportReportEntry;
import com.liferay.batch.engine.model.BatchEngineImportReportEntryModel;
import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.kernel.util.Validator;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the BatchEngineImportReportEntry service. Represents a row in the &quot;BatchEngineImportReportEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>BatchEngineImportReportEntryModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link BatchEngineImportReportEntryImpl}.
 * </p>
 *
 * @author Shuyang Zhou
 * @see BatchEngineImportReportEntryImpl
 * @generated
 */
public class BatchEngineImportReportEntryModelImpl
	extends BaseModelImpl<BatchEngineImportReportEntry>
	implements BatchEngineImportReportEntryModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a batch engine import report entry model instance should use the <code>BatchEngineImportReportEntry</code> interface instead.
	 */
	public static final String TABLE_NAME = "BatchEngineImportReportEntry";

	public static final Object[][] TABLE_COLUMNS = {
		{"mvccVersion", Types.BIGINT},
		{"batchEngineImportReportEntryId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"classNameId", Types.BIGINT},
		{"classPK", Types.BIGINT}, {"entityClassNameId", Types.BIGINT},
		{"entityExternalReferenceCode", Types.VARCHAR},
		{"error", Types.VARCHAR}, {"resolved", Types.BOOLEAN},
		{"type_", Types.INTEGER}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mvccVersion", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("batchEngineImportReportEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("classNameId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("classPK", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("entityClassNameId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("entityExternalReferenceCode", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("error", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("resolved", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("type_", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE =
		"create table BatchEngineImportReportEntry (mvccVersion LONG default 0 not null,batchEngineImportReportEntryId LONG not null primary key,companyId LONG,createDate DATE null,modifiedDate DATE null,classNameId LONG,classPK LONG,entityClassNameId LONG,entityExternalReferenceCode VARCHAR(75) null,error VARCHAR(75) null,resolved BOOLEAN,type_ INTEGER)";

	public static final String TABLE_SQL_DROP =
		"drop table BatchEngineImportReportEntry";

	public static final String ORDER_BY_JPQL =
		" ORDER BY batchEngineImportReportEntry.batchEngineImportReportEntryId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY BatchEngineImportReportEntry.batchEngineImportReportEntryId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CLASSNAMEID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CLASSPK_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long BATCHENGINEIMPORTREPORTENTRYID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public BatchEngineImportReportEntryModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _batchEngineImportReportEntryId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setBatchEngineImportReportEntryId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _batchEngineImportReportEntryId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return BatchEngineImportReportEntry.class;
	}

	@Override
	public String getModelClassName() {
		return BatchEngineImportReportEntry.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<BatchEngineImportReportEntry, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<BatchEngineImportReportEntry, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<BatchEngineImportReportEntry, Object>
				attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply(
					(BatchEngineImportReportEntry)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<BatchEngineImportReportEntry, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<BatchEngineImportReportEntry, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(BatchEngineImportReportEntry)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<BatchEngineImportReportEntry, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<BatchEngineImportReportEntry, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map
			<String, Function<BatchEngineImportReportEntry, Object>>
				_attributeGetterFunctions;

		static {
			Map<String, Function<BatchEngineImportReportEntry, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String,
						 Function<BatchEngineImportReportEntry, Object>>();

			attributeGetterFunctions.put(
				"mvccVersion", BatchEngineImportReportEntry::getMvccVersion);
			attributeGetterFunctions.put(
				"batchEngineImportReportEntryId",
				BatchEngineImportReportEntry::
					getBatchEngineImportReportEntryId);
			attributeGetterFunctions.put(
				"companyId", BatchEngineImportReportEntry::getCompanyId);
			attributeGetterFunctions.put(
				"createDate", BatchEngineImportReportEntry::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", BatchEngineImportReportEntry::getModifiedDate);
			attributeGetterFunctions.put(
				"classNameId", BatchEngineImportReportEntry::getClassNameId);
			attributeGetterFunctions.put(
				"classPK", BatchEngineImportReportEntry::getClassPK);
			attributeGetterFunctions.put(
				"entityClassNameId",
				BatchEngineImportReportEntry::getEntityClassNameId);
			attributeGetterFunctions.put(
				"entityExternalReferenceCode",
				BatchEngineImportReportEntry::getEntityExternalReferenceCode);
			attributeGetterFunctions.put(
				"error", BatchEngineImportReportEntry::getError);
			attributeGetterFunctions.put(
				"resolved", BatchEngineImportReportEntry::getResolved);
			attributeGetterFunctions.put(
				"type", BatchEngineImportReportEntry::getType);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map
			<String, BiConsumer<BatchEngineImportReportEntry, Object>>
				_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<BatchEngineImportReportEntry, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String, BiConsumer<BatchEngineImportReportEntry, ?>>();

			attributeSetterBiConsumers.put(
				"mvccVersion",
				(BiConsumer<BatchEngineImportReportEntry, Long>)
					BatchEngineImportReportEntry::setMvccVersion);
			attributeSetterBiConsumers.put(
				"batchEngineImportReportEntryId",
				(BiConsumer<BatchEngineImportReportEntry, Long>)
					BatchEngineImportReportEntry::
						setBatchEngineImportReportEntryId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<BatchEngineImportReportEntry, Long>)
					BatchEngineImportReportEntry::setCompanyId);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<BatchEngineImportReportEntry, Date>)
					BatchEngineImportReportEntry::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<BatchEngineImportReportEntry, Date>)
					BatchEngineImportReportEntry::setModifiedDate);
			attributeSetterBiConsumers.put(
				"classNameId",
				(BiConsumer<BatchEngineImportReportEntry, Long>)
					BatchEngineImportReportEntry::setClassNameId);
			attributeSetterBiConsumers.put(
				"classPK",
				(BiConsumer<BatchEngineImportReportEntry, Long>)
					BatchEngineImportReportEntry::setClassPK);
			attributeSetterBiConsumers.put(
				"entityClassNameId",
				(BiConsumer<BatchEngineImportReportEntry, Long>)
					BatchEngineImportReportEntry::setEntityClassNameId);
			attributeSetterBiConsumers.put(
				"entityExternalReferenceCode",
				(BiConsumer<BatchEngineImportReportEntry, String>)
					BatchEngineImportReportEntry::
						setEntityExternalReferenceCode);
			attributeSetterBiConsumers.put(
				"error",
				(BiConsumer<BatchEngineImportReportEntry, String>)
					BatchEngineImportReportEntry::setError);
			attributeSetterBiConsumers.put(
				"resolved",
				(BiConsumer<BatchEngineImportReportEntry, Boolean>)
					BatchEngineImportReportEntry::setResolved);
			attributeSetterBiConsumers.put(
				"type",
				(BiConsumer<BatchEngineImportReportEntry, Integer>)
					BatchEngineImportReportEntry::setType);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@Override
	public long getMvccVersion() {
		return _mvccVersion;
	}

	@Override
	public void setMvccVersion(long mvccVersion) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mvccVersion = mvccVersion;
	}

	@Override
	public long getBatchEngineImportReportEntryId() {
		return _batchEngineImportReportEntryId;
	}

	@Override
	public void setBatchEngineImportReportEntryId(
		long batchEngineImportReportEntryId) {

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_batchEngineImportReportEntryId = batchEngineImportReportEntryId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@Override
	public String getClassName() {
		if (getClassNameId() <= 0) {
			return "";
		}

		return PortalUtil.getClassName(getClassNameId());
	}

	@Override
	public void setClassName(String className) {
		long classNameId = 0;

		if (Validator.isNotNull(className)) {
			classNameId = PortalUtil.getClassNameId(className);
		}

		setClassNameId(classNameId);
	}

	@Override
	public long getClassNameId() {
		return _classNameId;
	}

	@Override
	public void setClassNameId(long classNameId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_classNameId = classNameId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalClassNameId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("classNameId"));
	}

	@Override
	public long getClassPK() {
		return _classPK;
	}

	@Override
	public void setClassPK(long classPK) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_classPK = classPK;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalClassPK() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("classPK"));
	}

	@Override
	public long getEntityClassNameId() {
		return _entityClassNameId;
	}

	@Override
	public void setEntityClassNameId(long entityClassNameId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_entityClassNameId = entityClassNameId;
	}

	@Override
	public String getEntityExternalReferenceCode() {
		if (_entityExternalReferenceCode == null) {
			return "";
		}
		else {
			return _entityExternalReferenceCode;
		}
	}

	@Override
	public void setEntityExternalReferenceCode(
		String entityExternalReferenceCode) {

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_entityExternalReferenceCode = entityExternalReferenceCode;
	}

	@Override
	public String getError() {
		if (_error == null) {
			return "";
		}
		else {
			return _error;
		}
	}

	@Override
	public void setError(String error) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_error = error;
	}

	@Override
	public boolean getResolved() {
		return _resolved;
	}

	@Override
	public boolean isResolved() {
		return _resolved;
	}

	@Override
	public void setResolved(boolean resolved) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_resolved = resolved;
	}

	@Override
	public int getType() {
		return _type;
	}

	@Override
	public void setType(int type) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_type = type;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), BatchEngineImportReportEntry.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public BatchEngineImportReportEntry toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, BatchEngineImportReportEntry>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		BatchEngineImportReportEntryImpl batchEngineImportReportEntryImpl =
			new BatchEngineImportReportEntryImpl();

		batchEngineImportReportEntryImpl.setMvccVersion(getMvccVersion());
		batchEngineImportReportEntryImpl.setBatchEngineImportReportEntryId(
			getBatchEngineImportReportEntryId());
		batchEngineImportReportEntryImpl.setCompanyId(getCompanyId());
		batchEngineImportReportEntryImpl.setCreateDate(getCreateDate());
		batchEngineImportReportEntryImpl.setModifiedDate(getModifiedDate());
		batchEngineImportReportEntryImpl.setClassNameId(getClassNameId());
		batchEngineImportReportEntryImpl.setClassPK(getClassPK());
		batchEngineImportReportEntryImpl.setEntityClassNameId(
			getEntityClassNameId());
		batchEngineImportReportEntryImpl.setEntityExternalReferenceCode(
			getEntityExternalReferenceCode());
		batchEngineImportReportEntryImpl.setError(getError());
		batchEngineImportReportEntryImpl.setResolved(isResolved());
		batchEngineImportReportEntryImpl.setType(getType());

		batchEngineImportReportEntryImpl.resetOriginalValues();

		return batchEngineImportReportEntryImpl;
	}

	@Override
	public BatchEngineImportReportEntry cloneWithOriginalValues() {
		BatchEngineImportReportEntryImpl batchEngineImportReportEntryImpl =
			new BatchEngineImportReportEntryImpl();

		batchEngineImportReportEntryImpl.setMvccVersion(
			this.<Long>getColumnOriginalValue("mvccVersion"));
		batchEngineImportReportEntryImpl.setBatchEngineImportReportEntryId(
			this.<Long>getColumnOriginalValue(
				"batchEngineImportReportEntryId"));
		batchEngineImportReportEntryImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		batchEngineImportReportEntryImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		batchEngineImportReportEntryImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		batchEngineImportReportEntryImpl.setClassNameId(
			this.<Long>getColumnOriginalValue("classNameId"));
		batchEngineImportReportEntryImpl.setClassPK(
			this.<Long>getColumnOriginalValue("classPK"));
		batchEngineImportReportEntryImpl.setEntityClassNameId(
			this.<Long>getColumnOriginalValue("entityClassNameId"));
		batchEngineImportReportEntryImpl.setEntityExternalReferenceCode(
			this.<String>getColumnOriginalValue("entityExternalReferenceCode"));
		batchEngineImportReportEntryImpl.setError(
			this.<String>getColumnOriginalValue("error"));
		batchEngineImportReportEntryImpl.setResolved(
			this.<Boolean>getColumnOriginalValue("resolved"));
		batchEngineImportReportEntryImpl.setType(
			this.<Integer>getColumnOriginalValue("type_"));

		return batchEngineImportReportEntryImpl;
	}

	@Override
	public int compareTo(
		BatchEngineImportReportEntry batchEngineImportReportEntry) {

		long primaryKey = batchEngineImportReportEntry.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof BatchEngineImportReportEntry)) {
			return false;
		}

		BatchEngineImportReportEntry batchEngineImportReportEntry =
			(BatchEngineImportReportEntry)object;

		long primaryKey = batchEngineImportReportEntry.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<BatchEngineImportReportEntry> toCacheModel() {
		BatchEngineImportReportEntryCacheModel
			batchEngineImportReportEntryCacheModel =
				new BatchEngineImportReportEntryCacheModel();

		batchEngineImportReportEntryCacheModel.mvccVersion = getMvccVersion();

		batchEngineImportReportEntryCacheModel.batchEngineImportReportEntryId =
			getBatchEngineImportReportEntryId();

		batchEngineImportReportEntryCacheModel.companyId = getCompanyId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			batchEngineImportReportEntryCacheModel.createDate =
				createDate.getTime();
		}
		else {
			batchEngineImportReportEntryCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			batchEngineImportReportEntryCacheModel.modifiedDate =
				modifiedDate.getTime();
		}
		else {
			batchEngineImportReportEntryCacheModel.modifiedDate =
				Long.MIN_VALUE;
		}

		batchEngineImportReportEntryCacheModel.classNameId = getClassNameId();

		batchEngineImportReportEntryCacheModel.classPK = getClassPK();

		batchEngineImportReportEntryCacheModel.entityClassNameId =
			getEntityClassNameId();

		batchEngineImportReportEntryCacheModel.entityExternalReferenceCode =
			getEntityExternalReferenceCode();

		String entityExternalReferenceCode =
			batchEngineImportReportEntryCacheModel.entityExternalReferenceCode;

		if ((entityExternalReferenceCode != null) &&
			(entityExternalReferenceCode.length() == 0)) {

			batchEngineImportReportEntryCacheModel.entityExternalReferenceCode =
				null;
		}

		batchEngineImportReportEntryCacheModel.error = getError();

		String error = batchEngineImportReportEntryCacheModel.error;

		if ((error != null) && (error.length() == 0)) {
			batchEngineImportReportEntryCacheModel.error = null;
		}

		batchEngineImportReportEntryCacheModel.resolved = isResolved();

		batchEngineImportReportEntryCacheModel.type = getType();

		return batchEngineImportReportEntryCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<BatchEngineImportReportEntry, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<BatchEngineImportReportEntry, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<BatchEngineImportReportEntry, Object>
				attributeGetterFunction = entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(BatchEngineImportReportEntry)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function
			<InvocationHandler, BatchEngineImportReportEntry>
				_escapedModelProxyProviderFunction =
					ProxyUtil.getProxyProviderFunction(
						BatchEngineImportReportEntry.class, ModelWrapper.class);

	}

	private long _mvccVersion;
	private long _batchEngineImportReportEntryId;
	private long _companyId;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _classNameId;
	private long _classPK;
	private long _entityClassNameId;
	private String _entityExternalReferenceCode;
	private String _error;
	private boolean _resolved;
	private int _type;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<BatchEngineImportReportEntry, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((BatchEngineImportReportEntry)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("mvccVersion", _mvccVersion);
		_columnOriginalValues.put(
			"batchEngineImportReportEntryId", _batchEngineImportReportEntryId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("classNameId", _classNameId);
		_columnOriginalValues.put("classPK", _classPK);
		_columnOriginalValues.put("entityClassNameId", _entityClassNameId);
		_columnOriginalValues.put(
			"entityExternalReferenceCode", _entityExternalReferenceCode);
		_columnOriginalValues.put("error", _error);
		_columnOriginalValues.put("resolved", _resolved);
		_columnOriginalValues.put("type_", _type);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("type_", "type");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("mvccVersion", 1L);

		columnBitmasks.put("batchEngineImportReportEntryId", 2L);

		columnBitmasks.put("companyId", 4L);

		columnBitmasks.put("createDate", 8L);

		columnBitmasks.put("modifiedDate", 16L);

		columnBitmasks.put("classNameId", 32L);

		columnBitmasks.put("classPK", 64L);

		columnBitmasks.put("entityClassNameId", 128L);

		columnBitmasks.put("entityExternalReferenceCode", 256L);

		columnBitmasks.put("error", 512L);

		columnBitmasks.put("resolved", 1024L);

		columnBitmasks.put("type_", 2048L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private BatchEngineImportReportEntry _escapedModel;

}