/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.portal.service.base;

import aQute.bnd.annotation.ProviderType;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBFactoryUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.model.PersistedModel;
import com.liferay.portal.model.RecentLayout;
import com.liferay.portal.service.BaseLocalServiceImpl;
import com.liferay.portal.service.PersistedModelLocalServiceRegistry;
import com.liferay.portal.service.RecentLayoutLocalService;
import com.liferay.portal.service.persistence.RecentLayoutPersistence;
import com.liferay.portal.util.PortalUtil;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the recent layout local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.portal.service.impl.RecentLayoutLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.liferay.portal.service.impl.RecentLayoutLocalServiceImpl
 * @see com.liferay.portal.service.RecentLayoutLocalServiceUtil
 * @generated
 */
@ProviderType
public abstract class RecentLayoutLocalServiceBaseImpl
	extends BaseLocalServiceImpl implements RecentLayoutLocalService,
		IdentifiableOSGiService {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.liferay.portal.service.RecentLayoutLocalServiceUtil} to access the recent layout local service.
	 */

	/**
	 * Adds the recent layout to the database. Also notifies the appropriate model listeners.
	 *
	 * @param recentLayout the recent layout
	 * @return the recent layout that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public RecentLayout addRecentLayout(RecentLayout recentLayout) {
		recentLayout.setNew(true);

		return recentLayoutPersistence.update(recentLayout);
	}

	/**
	 * Creates a new recent layout with the primary key. Does not add the recent layout to the database.
	 *
	 * @param recentLayoutId the primary key for the new recent layout
	 * @return the new recent layout
	 */
	@Override
	public RecentLayout createRecentLayout(long recentLayoutId) {
		return recentLayoutPersistence.create(recentLayoutId);
	}

	/**
	 * Deletes the recent layout with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param recentLayoutId the primary key of the recent layout
	 * @return the recent layout that was removed
	 * @throws PortalException if a recent layout with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public RecentLayout deleteRecentLayout(long recentLayoutId)
		throws PortalException {
		return recentLayoutPersistence.remove(recentLayoutId);
	}

	/**
	 * Deletes the recent layout from the database. Also notifies the appropriate model listeners.
	 *
	 * @param recentLayout the recent layout
	 * @return the recent layout that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public RecentLayout deleteRecentLayout(RecentLayout recentLayout) {
		return recentLayoutPersistence.remove(recentLayout);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(RecentLayout.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return recentLayoutPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.liferay.portal.model.impl.RecentLayoutModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end) {
		return recentLayoutPersistence.findWithDynamicQuery(dynamicQuery,
			start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.liferay.portal.model.impl.RecentLayoutModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end, OrderByComparator<T> orderByComparator) {
		return recentLayoutPersistence.findWithDynamicQuery(dynamicQuery,
			start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return recentLayoutPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery,
		Projection projection) {
		return recentLayoutPersistence.countWithDynamicQuery(dynamicQuery,
			projection);
	}

	@Override
	public RecentLayout fetchRecentLayout(long recentLayoutId) {
		return recentLayoutPersistence.fetchByPrimaryKey(recentLayoutId);
	}

	/**
	 * Returns the recent layout with the primary key.
	 *
	 * @param recentLayoutId the primary key of the recent layout
	 * @return the recent layout
	 * @throws PortalException if a recent layout with the primary key could not be found
	 */
	@Override
	public RecentLayout getRecentLayout(long recentLayoutId)
		throws PortalException {
		return recentLayoutPersistence.findByPrimaryKey(recentLayoutId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery = new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(com.liferay.portal.service.RecentLayoutLocalServiceUtil.getService());
		actionableDynamicQuery.setClass(RecentLayout.class);
		actionableDynamicQuery.setClassLoader(getClassLoader());

		actionableDynamicQuery.setPrimaryKeyPropertyName("recentLayoutId");

		return actionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {
		actionableDynamicQuery.setBaseLocalService(com.liferay.portal.service.RecentLayoutLocalServiceUtil.getService());
		actionableDynamicQuery.setClass(RecentLayout.class);
		actionableDynamicQuery.setClassLoader(getClassLoader());

		actionableDynamicQuery.setPrimaryKeyPropertyName("recentLayoutId");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {
		return recentLayoutLocalService.deleteRecentLayout((RecentLayout)persistedModel);
	}

	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {
		return recentLayoutPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the recent layouts.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.liferay.portal.model.impl.RecentLayoutModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param start the lower bound of the range of recent layouts
	 * @param end the upper bound of the range of recent layouts (not inclusive)
	 * @return the range of recent layouts
	 */
	@Override
	public List<RecentLayout> getRecentLayouts(int start, int end) {
		return recentLayoutPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of recent layouts.
	 *
	 * @return the number of recent layouts
	 */
	@Override
	public int getRecentLayoutsCount() {
		return recentLayoutPersistence.countAll();
	}

	/**
	 * Updates the recent layout in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param recentLayout the recent layout
	 * @return the recent layout that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public RecentLayout updateRecentLayout(RecentLayout recentLayout) {
		return recentLayoutPersistence.update(recentLayout);
	}

	/**
	 * Returns the recent layout local service.
	 *
	 * @return the recent layout local service
	 */
	public RecentLayoutLocalService getRecentLayoutLocalService() {
		return recentLayoutLocalService;
	}

	/**
	 * Sets the recent layout local service.
	 *
	 * @param recentLayoutLocalService the recent layout local service
	 */
	public void setRecentLayoutLocalService(
		RecentLayoutLocalService recentLayoutLocalService) {
		this.recentLayoutLocalService = recentLayoutLocalService;
	}

	/**
	 * Returns the recent layout persistence.
	 *
	 * @return the recent layout persistence
	 */
	public RecentLayoutPersistence getRecentLayoutPersistence() {
		return recentLayoutPersistence;
	}

	/**
	 * Sets the recent layout persistence.
	 *
	 * @param recentLayoutPersistence the recent layout persistence
	 */
	public void setRecentLayoutPersistence(
		RecentLayoutPersistence recentLayoutPersistence) {
		this.recentLayoutPersistence = recentLayoutPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	public void afterPropertiesSet() {
		persistedModelLocalServiceRegistry.register("com.liferay.portal.model.RecentLayout",
			recentLayoutLocalService);
	}

	public void destroy() {
		persistedModelLocalServiceRegistry.unregister(
			"com.liferay.portal.model.RecentLayout");
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return RecentLayoutLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return RecentLayout.class;
	}

	protected String getModelClassName() {
		return RecentLayout.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = recentLayoutPersistence.getDataSource();

			DB db = DBFactoryUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = com.liferay.portal.service.RecentLayoutLocalService.class)
	protected RecentLayoutLocalService recentLayoutLocalService;
	@BeanReference(type = RecentLayoutPersistence.class)
	protected RecentLayoutPersistence recentLayoutPersistence;
	@BeanReference(type = com.liferay.counter.service.CounterLocalService.class)
	protected com.liferay.counter.service.CounterLocalService counterLocalService;
	@BeanReference(type = PersistedModelLocalServiceRegistry.class)
	protected PersistedModelLocalServiceRegistry persistedModelLocalServiceRegistry;
}