/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.gsportal.core.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Client service. Represents a row in the &quot;Core_Client&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.gsportal.core.model.impl.ClientModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.gsportal.core.model.impl.ClientImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Client
 * @see com.liferay.gsportal.core.model.impl.ClientImpl
 * @see com.liferay.gsportal.core.model.impl.ClientModelImpl
 * @generated
 */
@ProviderType
public interface ClientModel extends BaseModel<Client>, ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a client model instance should use the {@link Client} interface instead.
	 */

	/**
	 * Returns the primary key of this client.
	 *
	 * @return the primary key of this client
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this client.
	 *
	 * @param primaryKey the primary key of this client
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the client ID of this client.
	 *
	 * @return the client ID of this client
	 */
	public long getClientId();

	/**
	 * Sets the client ID of this client.
	 *
	 * @param clientId the client ID of this client
	 */
	public void setClientId(long clientId);

	/**
	 * Returns the company ID of this client.
	 *
	 * @return the company ID of this client
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this client.
	 *
	 * @param companyId the company ID of this client
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the create date of this client.
	 *
	 * @return the create date of this client
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this client.
	 *
	 * @param createDate the create date of this client
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this client.
	 *
	 * @return the modified date of this client
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this client.
	 *
	 * @param modifiedDate the modified date of this client
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the parent client ID of this client.
	 *
	 * @return the parent client ID of this client
	 */
	public long getParentClientId();

	/**
	 * Sets the parent client ID of this client.
	 *
	 * @param parentClientId the parent client ID of this client
	 */
	public void setParentClientId(long parentClientId);

	/**
	 * Returns the name of this client.
	 *
	 * @return the name of this client
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this client.
	 *
	 * @param name the name of this client
	 */
	public void setName(String name);

	/**
	 * Returns the description of this client.
	 *
	 * @return the description of this client
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this client.
	 *
	 * @param description the description of this client
	 */
	public void setDescription(String description);

	/**
	 * Returns the dashboard url of this client.
	 *
	 * @return the dashboard url of this client
	 */
	@AutoEscape
	public String getDashboardUrl();

	/**
	 * Sets the dashboard url of this client.
	 *
	 * @param dashboardUrl the dashboard url of this client
	 */
	public void setDashboardUrl(String dashboardUrl);

	/**
	 * Returns the logo ID of this client.
	 *
	 * @return the logo ID of this client
	 */
	public long getLogoId();

	/**
	 * Sets the logo ID of this client.
	 *
	 * @param logoId the logo ID of this client
	 */
	public void setLogoId(long logoId);

	/**
	 * Returns the logo url of this client.
	 *
	 * @return the logo url of this client
	 */
	@AutoEscape
	public String getLogoUrl();

	/**
	 * Sets the logo url of this client.
	 *
	 * @param logoUrl the logo url of this client
	 */
	public void setLogoUrl(String logoUrl);

	/**
	 * Returns the website url of this client.
	 *
	 * @return the website url of this client
	 */
	@AutoEscape
	public String getWebsiteUrl();

	/**
	 * Sets the website url of this client.
	 *
	 * @param websiteUrl the website url of this client
	 */
	public void setWebsiteUrl(String websiteUrl);

	/**
	 * Returns the address ID of this client.
	 *
	 * @return the address ID of this client
	 */
	public long getAddressId();

	/**
	 * Sets the address ID of this client.
	 *
	 * @param addressId the address ID of this client
	 */
	public void setAddressId(long addressId);

	/**
	 * Returns the active of this client.
	 *
	 * @return the active of this client
	 */
	public boolean getActive();

	/**
	 * Returns <code>true</code> if this client is active.
	 *
	 * @return <code>true</code> if this client is active; <code>false</code> otherwise
	 */
	public boolean isActive();

	/**
	 * Sets whether this client is active.
	 *
	 * @param active the active of this client
	 */
	public void setActive(boolean active);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Client client);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Client> toCacheModel();

	@Override
	public Client toEscapedModel();

	@Override
	public Client toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}