/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.gsportal.core.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Engagement service. Represents a row in the &quot;Core_Engagement&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.gsportal.core.model.impl.EngagementModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.gsportal.core.model.impl.EngagementImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Engagement
 * @see com.liferay.gsportal.core.model.impl.EngagementImpl
 * @see com.liferay.gsportal.core.model.impl.EngagementModelImpl
 * @generated
 */
@ProviderType
public interface EngagementModel extends BaseModel<Engagement>, ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a engagement model instance should use the {@link Engagement} interface instead.
	 */

	/**
	 * Returns the primary key of this engagement.
	 *
	 * @return the primary key of this engagement
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this engagement.
	 *
	 * @param primaryKey the primary key of this engagement
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the engagement ID of this engagement.
	 *
	 * @return the engagement ID of this engagement
	 */
	public long getEngagementId();

	/**
	 * Sets the engagement ID of this engagement.
	 *
	 * @param engagementId the engagement ID of this engagement
	 */
	public void setEngagementId(long engagementId);

	/**
	 * Returns the company ID of this engagement.
	 *
	 * @return the company ID of this engagement
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this engagement.
	 *
	 * @param companyId the company ID of this engagement
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the create date of this engagement.
	 *
	 * @return the create date of this engagement
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this engagement.
	 *
	 * @param createDate the create date of this engagement
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this engagement.
	 *
	 * @return the modified date of this engagement
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this engagement.
	 *
	 * @param modifiedDate the modified date of this engagement
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the calendar booking ID of this engagement.
	 *
	 * @return the calendar booking ID of this engagement
	 */
	public long getCalendarBookingId();

	/**
	 * Sets the calendar booking ID of this engagement.
	 *
	 * @param calendarBookingId the calendar booking ID of this engagement
	 */
	public void setCalendarBookingId(long calendarBookingId);

	/**
	 * Returns the client ID of this engagement.
	 *
	 * @return the client ID of this engagement
	 */
	public long getClientId();

	/**
	 * Sets the client ID of this engagement.
	 *
	 * @param clientId the client ID of this engagement
	 */
	public void setClientId(long clientId);

	/**
	 * Returns the project ID of this engagement.
	 *
	 * @return the project ID of this engagement
	 */
	public long getProjectId();

	/**
	 * Sets the project ID of this engagement.
	 *
	 * @param projectId the project ID of this engagement
	 */
	public void setProjectId(long projectId);

	/**
	 * Returns the title of this engagement.
	 *
	 * @return the title of this engagement
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this engagement.
	 *
	 * @param title the title of this engagement
	 */
	public void setTitle(String title);

	/**
	 * Returns the description of this engagement.
	 *
	 * @return the description of this engagement
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this engagement.
	 *
	 * @param description the description of this engagement
	 */
	public void setDescription(String description);

	/**
	 * Returns the lead user ID of this engagement.
	 *
	 * @return the lead user ID of this engagement
	 */
	public long getLeadUserId();

	/**
	 * Sets the lead user ID of this engagement.
	 *
	 * @param leadUserId the lead user ID of this engagement
	 */
	public void setLeadUserId(long leadUserId);

	/**
	 * Returns the lead user uuid of this engagement.
	 *
	 * @return the lead user uuid of this engagement
	 */
	public String getLeadUserUuid();

	/**
	 * Sets the lead user uuid of this engagement.
	 *
	 * @param leadUserUuid the lead user uuid of this engagement
	 */
	public void setLeadUserUuid(String leadUserUuid);

	/**
	 * Returns the lead name of this engagement.
	 *
	 * @return the lead name of this engagement
	 */
	@AutoEscape
	public String getLeadName();

	/**
	 * Sets the lead name of this engagement.
	 *
	 * @param leadName the lead name of this engagement
	 */
	public void setLeadName(String leadName);

	/**
	 * Returns the type category ID of this engagement.
	 *
	 * @return the type category ID of this engagement
	 */
	public long getTypeCategoryId();

	/**
	 * Sets the type category ID of this engagement.
	 *
	 * @param typeCategoryId the type category ID of this engagement
	 */
	public void setTypeCategoryId(long typeCategoryId);

	/**
	 * Returns the difficulty ID of this engagement.
	 *
	 * @return the difficulty ID of this engagement
	 */
	public int getDifficultyId();

	/**
	 * Sets the difficulty ID of this engagement.
	 *
	 * @param difficultyId the difficulty ID of this engagement
	 */
	public void setDifficultyId(int difficultyId);

	/**
	 * Returns the progress status ID of this engagement.
	 *
	 * @return the progress status ID of this engagement
	 */
	public int getProgressStatusId();

	/**
	 * Sets the progress status ID of this engagement.
	 *
	 * @param progressStatusId the progress status ID of this engagement
	 */
	public void setProgressStatusId(int progressStatusId);

	/**
	 * Returns the approval status ID of this engagement.
	 *
	 * @return the approval status ID of this engagement
	 */
	public int getApprovalStatusId();

	/**
	 * Sets the approval status ID of this engagement.
	 *
	 * @param approvalStatusId the approval status ID of this engagement
	 */
	public void setApprovalStatusId(int approvalStatusId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Engagement engagement);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Engagement> toCacheModel();

	@Override
	public Engagement toEscapedModel();

	@Override
	public Engagement toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}