/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.gsportal.core.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the MemberOf service. Represents a row in the &quot;Core_MemberOf&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.gsportal.core.model.impl.MemberOfModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.gsportal.core.model.impl.MemberOfImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see MemberOf
 * @see com.liferay.gsportal.core.model.impl.MemberOfImpl
 * @see com.liferay.gsportal.core.model.impl.MemberOfModelImpl
 * @generated
 */
@ProviderType
public interface MemberOfModel extends BaseModel<MemberOf>, ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a member of model instance should use the {@link MemberOf} interface instead.
	 */

	/**
	 * Returns the primary key of this member of.
	 *
	 * @return the primary key of this member of
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this member of.
	 *
	 * @param primaryKey the primary key of this member of
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the member of ID of this member of.
	 *
	 * @return the member of ID of this member of
	 */
	public long getMemberOfId();

	/**
	 * Sets the member of ID of this member of.
	 *
	 * @param memberOfId the member of ID of this member of
	 */
	public void setMemberOfId(long memberOfId);

	/**
	 * Returns the company ID of this member of.
	 *
	 * @return the company ID of this member of
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this member of.
	 *
	 * @param companyId the company ID of this member of
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the create date of this member of.
	 *
	 * @return the create date of this member of
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this member of.
	 *
	 * @param createDate the create date of this member of
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the user ID of this member of.
	 *
	 * @return the user ID of this member of
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this member of.
	 *
	 * @param userId the user ID of this member of
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this member of.
	 *
	 * @return the user uuid of this member of
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this member of.
	 *
	 * @param userUuid the user uuid of this member of
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the client ID of this member of.
	 *
	 * @return the client ID of this member of
	 */
	public long getClientId();

	/**
	 * Sets the client ID of this member of.
	 *
	 * @param clientId the client ID of this member of
	 */
	public void setClientId(long clientId);

	/**
	 * Returns the project ID of this member of.
	 *
	 * @return the project ID of this member of
	 */
	public long getProjectId();

	/**
	 * Sets the project ID of this member of.
	 *
	 * @param projectId the project ID of this member of
	 */
	public void setProjectId(long projectId);

	/**
	 * Returns the engagement ID of this member of.
	 *
	 * @return the engagement ID of this member of
	 */
	public long getEngagementId();

	/**
	 * Sets the engagement ID of this member of.
	 *
	 * @param engagementId the engagement ID of this member of
	 */
	public void setEngagementId(long engagementId);

	/**
	 * Returns the member role ID of this member of.
	 *
	 * @return the member role ID of this member of
	 */
	public int getMemberRoleId();

	/**
	 * Sets the member role ID of this member of.
	 *
	 * @param memberRoleId the member role ID of this member of
	 */
	public void setMemberRoleId(int memberRoleId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(MemberOf memberOf);

	@Override
	public int hashCode();

	@Override
	public CacheModel<MemberOf> toCacheModel();

	@Override
	public MemberOf toEscapedModel();

	@Override
	public MemberOf toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}