/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.gsportal.core.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Project service. Represents a row in the &quot;Core_Project&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.gsportal.core.model.impl.ProjectModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.gsportal.core.model.impl.ProjectImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Project
 * @see com.liferay.gsportal.core.model.impl.ProjectImpl
 * @see com.liferay.gsportal.core.model.impl.ProjectModelImpl
 * @generated
 */
@ProviderType
public interface ProjectModel extends BaseModel<Project>, ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a project model instance should use the {@link Project} interface instead.
	 */

	/**
	 * Returns the primary key of this project.
	 *
	 * @return the primary key of this project
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this project.
	 *
	 * @param primaryKey the primary key of this project
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the project ID of this project.
	 *
	 * @return the project ID of this project
	 */
	public long getProjectId();

	/**
	 * Sets the project ID of this project.
	 *
	 * @param projectId the project ID of this project
	 */
	public void setProjectId(long projectId);

	/**
	 * Returns the company ID of this project.
	 *
	 * @return the company ID of this project
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this project.
	 *
	 * @param companyId the company ID of this project
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the create date of this project.
	 *
	 * @return the create date of this project
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this project.
	 *
	 * @param createDate the create date of this project
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this project.
	 *
	 * @return the modified date of this project
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this project.
	 *
	 * @param modifiedDate the modified date of this project
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the client ID of this project.
	 *
	 * @return the client ID of this project
	 */
	public long getClientId();

	/**
	 * Sets the client ID of this project.
	 *
	 * @param clientId the client ID of this project
	 */
	public void setClientId(long clientId);

	/**
	 * Returns the calendar ID of this project.
	 *
	 * @return the calendar ID of this project
	 */
	public long getCalendarId();

	/**
	 * Sets the calendar ID of this project.
	 *
	 * @param calendarId the calendar ID of this project
	 */
	public void setCalendarId(long calendarId);

	/**
	 * Returns the name of this project.
	 *
	 * @return the name of this project
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this project.
	 *
	 * @param name the name of this project
	 */
	public void setName(String name);

	/**
	 * Returns the description of this project.
	 *
	 * @return the description of this project
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this project.
	 *
	 * @param description the description of this project
	 */
	public void setDescription(String description);

	/**
	 * Returns the dashboard url of this project.
	 *
	 * @return the dashboard url of this project
	 */
	@AutoEscape
	public String getDashboardUrl();

	/**
	 * Sets the dashboard url of this project.
	 *
	 * @param dashboardUrl the dashboard url of this project
	 */
	public void setDashboardUrl(String dashboardUrl);

	/**
	 * Returns the lesa project key of this project.
	 *
	 * @return the lesa project key of this project
	 */
	@AutoEscape
	public String getLesaProjectKey();

	/**
	 * Sets the lesa project key of this project.
	 *
	 * @param lesaProjectKey the lesa project key of this project
	 */
	public void setLesaProjectKey(String lesaProjectKey);

	/**
	 * Returns the logo ID of this project.
	 *
	 * @return the logo ID of this project
	 */
	public long getLogoId();

	/**
	 * Sets the logo ID of this project.
	 *
	 * @param logoId the logo ID of this project
	 */
	public void setLogoId(long logoId);

	/**
	 * Returns the logo url of this project.
	 *
	 * @return the logo url of this project
	 */
	@AutoEscape
	public String getLogoUrl();

	/**
	 * Sets the logo url of this project.
	 *
	 * @param logoUrl the logo url of this project
	 */
	public void setLogoUrl(String logoUrl);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Project project);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Project> toCacheModel();

	@Override
	public Project toEscapedModel();

	@Override
	public Project toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}