/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.gsportal.core.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the StaffMember service. Represents a row in the &quot;Core_StaffMember&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.gsportal.core.model.impl.StaffMemberModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.gsportal.core.model.impl.StaffMemberImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see StaffMember
 * @see com.liferay.gsportal.core.model.impl.StaffMemberImpl
 * @see com.liferay.gsportal.core.model.impl.StaffMemberModelImpl
 * @generated
 */
@ProviderType
public interface StaffMemberModel extends BaseModel<StaffMember>, ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a staff member model instance should use the {@link StaffMember} interface instead.
	 */

	/**
	 * Returns the primary key of this staff member.
	 *
	 * @return the primary key of this staff member
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this staff member.
	 *
	 * @param primaryKey the primary key of this staff member
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the user ID of this staff member.
	 *
	 * @return the user ID of this staff member
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this staff member.
	 *
	 * @param userId the user ID of this staff member
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this staff member.
	 *
	 * @return the user uuid of this staff member
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this staff member.
	 *
	 * @param userUuid the user uuid of this staff member
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the company ID of this staff member.
	 *
	 * @return the company ID of this staff member
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this staff member.
	 *
	 * @param companyId the company ID of this staff member
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the employee type of this staff member.
	 *
	 * @return the employee type of this staff member
	 */
	public int getEmployeeType();

	/**
	 * Sets the employee type of this staff member.
	 *
	 * @param employeeType the employee type of this staff member
	 */
	public void setEmployeeType(int employeeType);

	/**
	 * Returns the employer name of this staff member.
	 *
	 * @return the employer name of this staff member
	 */
	@AutoEscape
	public String getEmployerName();

	/**
	 * Sets the employer name of this staff member.
	 *
	 * @param employerName the employer name of this staff member
	 */
	public void setEmployerName(String employerName);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(StaffMember staffMember);

	@Override
	public int hashCode();

	@Override
	public CacheModel<StaffMember> toCacheModel();

	@Override
	public StaffMember toEscapedModel();

	@Override
	public StaffMember toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}